# Generated by Django 3.0 on 2020-05-16 17:54

from django.db import migrations
import weather.models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=weather.models.CityField(max_length=25),
        ),
    ]
